config/routes.rb
Rails.application.routes.draw do
  
  get '/angular', to: 'static_pages#angular' # Hello World
  
  root 'static_pages#home'
  
  get  '/help',    to: 'static_pages#help', as: 'helf' #esse helf serve para usar no helf_path e helf_url
  
  get  '/about',   to: 'static_pages#about'
  
  get  '/contact', to: 'static_pages#contact'
  
  get '/signup', to: 'users#new'
  
  post '/signup', to: 'users#create'
  
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  
  post 'authenticate_user', to: 'authentication#authenticate_user'
  post 'authenticate_aluno', to: 'authentication#authenticate_aluno'

  get 'alterar_periodo', to: 'alunos#get_alterar_periodo'
  post 'alterar_periodo', to: 'alunos#alterar_periodo'

  resources :users
  resources :alunos do
    get 'edit_password', to: 'alunos#edit_password'
    patch 'update_password', to: 'alunos#update_password'
    resources :kits,              shallow: :true, except: [:index] do
      resource :download, only: [:show]
    end
  end
  resources :feeds, only: [:create, :index]
  resources :kit_types
  
  get '/kits', to: 'kits#index'

end

app/controllers/kit_types_controller.rb
class KitTypesController < ApplicationController
    
    before_action :logged_in_user, if: -> { !json_request? }

    def index
      @kit_types = KitType.all
    end
    
    def new
        @kit_type = KitType.new
    end
    
    def create
        @kit_type = KitType.new(kit_type_params)
        
        if @kit_type.save
            flash[:success] = "Kit Type created!"
            redirect_to @kit_type
        else
            render 'new'
        end
    end
    
    def show
        @kit_type = KitType.find(params[:id])
    end
    
    def edit
        @kit_type = KitType.find(params[:id])
    end
    
    def update
      @kit_type = KitType.find(params[:id])
      if @kit_type.update_attributes(kit_type_params)
        flash[:success] = "Tipo de Caixa atualizado"
        redirect_to @kit_type    
      else
      render 'edit'
      end
    end
    
    def destroy
      KitType.find(params[:id]).destroy
      flash[:success] = "Kit excluído!"
      redirect_to root_path
    end
    
    private
 
        def kit_type_params
            params.require(:kit_type).permit(:type_name)
        end
      
        def json_request?
          request.format.json?
        end
end

app/views/kit_types/_form_kit_type.html.erb
<%= form_for(@kit_type, url: yield(:path)) do |f| %>

  <%= render 'shared/error_messages', object: f.object %>

  <%= f.label :nome %>
  <%= f.text_field :type_name, class: 'form-control' %>

  <%= f.submit yield(:button_text), class: "btn btn-primary" %>
<% end %>

app/views/kit_types/_kit_type.html.erb
<li id="kit_type-<%= kit_type.id %>">
  <%= link_to image_tag("toolbox-icon.png", size:"50", alt: "Kit Image", class:"gravatar"), kit_type %>
  <span class="user"><%= link_to kit_type.type_name, kit_type %></span>
  <span class="timestamp">
    <br>
  </span>
</li>

app/views/kit_types/edit.html.erb
<% provide(:title, 'Editar Tipo de Caixa') %>
<% provide(:button_text, 'Confirmar Alterações') %>
<% provide(:path, kit_type_path(@kit_type)) %>

<div class="row">
    <div class="col-md-6 col-md-offset-3">
      <h1> Editar Tipo de Caixa </h1>
        <%= render 'form_kit_type' %>
    </div>
</div>

app/views/kit_types/index.html.erb
<% provide(:title, 'Tipos de Caixa') %>
<h1>Tipos de Caixa</h1>

<div>
    <%= link_to "Cadastrar Tipo de Caixa", new_kit_type_path, class: "btn btn-lg btn-primary", style: "margin-left:30px; margin-bottom:30px"%>
</div>

<ul class="users">
    <%= render @kit_types %>
</ul>

app/views/kit_types/new.html.erb
<% provide(:title, 'Cadastrar Tipo de Caixa') %>
<% provide(:button_text, 'Cadastrar') %>
<% provide(:path, kit_types_path) %>


<div class="row">
    <div class="col-md-6 col-md-offset-3">
      <h1> Cadastrar Tipo de Caixa</h1>
      <%= render 'form_kit_type' %>
    </div>
</div>

app/views/kit_types/show.html.erb
<% provide(:title, @kit_type.type_name) %>
<div class="row">
  <aside class="col-md-4">

    <section class="user_info">
      <h1>
          <div style="margin-bottom: 10px">
            <%= @kit_type.type_name %>
          </div>
          <div>
            <% if current_user.admin? %>
               <%= link_to "Editar Tipo de Caixa", edit_kit_type_path(@kit_type), class: 'btn btn-primary', style: 'float: none'%>
               <%= link_to "Excluir Tipo de Caixa", @kit_type, #analogous kit_path(@kit)
               method: :delete, data: { confirm: "Você tem certeza que deseja excluir #{@kit_type.type_name}?" }, class: 'btn btn-danger', style: 'float: none'%>
            <% end %>
            </div>
      </h1>
    </section>
  </aside>
</div>