config/routes.rb
Rails.application.routes.draw do
  
  get '/angular', to: 'static_pages#angular' # Hello World
  
  root 'static_pages#home'
  
  get  '/help',    to: 'static_pages#help', as: 'helf' #esse helf serve para usar no helf_path e helf_url
  
  get  '/about',   to: 'static_pages#about'
  
  get  '/contact', to: 'static_pages#contact'
  
  get '/signup', to: 'users#new'
  
  post '/signup', to: 'users#create'
  
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  
  post 'authenticate_user', to: 'authentication#authenticate_user'
  post 'authenticate_aluno', to: 'authentication#authenticate_aluno'

  get 'alterar_periodo', to: 'alunos#get_alterar_periodo'
  post 'alterar_periodo', to: 'alunos#alterar_periodo'

  resources :users
  resources :alunos do
    get 'edit_password', to: 'alunos#edit_password'
    patch 'update_password', to: 'alunos#update_password'
    resources :kits,              shallow: :true, except: [:index] do
      resource :download, only: [:show]
    end
  end
  resources :feeds, only: [:create, :index]
  resources :kit_types
  
  get '/kits', to: 'kits#index'

end

app/models/aluno.rb
class Aluno < ApplicationRecord
  has_many :kits, dependent: :destroy
  has_many :feeds, :through => :kits
  default_scope -> { order(nome: :asc) }
  before_save { self.email = email.downcase }
  
  validates(:nome, presence: true, length: { maximum: 50 })
  validates :matricula, presence: true, length: { maximum: 12 }, uniqueness: { case_sensitive: false }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, if: :password_digest_changed?
  validates :periodo, length: { maximum: 20 }
end

app/controllers/alunos_controller.rb
class AlunosController < ApplicationController
  
   before_action :logged_in_user

  def index
    #@alunos = Aluno.paginate(page: params[:page])
    @q = Aluno.ransack(params[:q])
    @alunos = @q.result(distinct: true).paginate(page: params[:page], :per_page => 10)
  end
  
  def create
    @aluno = Aluno.new(aluno_params)
    if @aluno.save
      flash[:success] = "Aluno criado!"
      redirect_to @aluno #redirect_to aluno_url(@aluno)
      # Handle a successful save.
    else
      render 'new'
    end
  end
  
  def new
    @aluno = Aluno.new
  end
  
  def show
    @aluno = Aluno.find(params[:id])
    @kits = @aluno.kits.paginate(page: params[:page], :per_page => 40)
    @feeds = @aluno.feeds.paginate(page: params[:page], :per_page => 3)
  end
  
  def destroy
    Aluno.find(params[:id]).destroy
    flash[:success] = "Aluno excluído!"
    redirect_to alunos_url
  end
  
  def edit
    @aluno = Aluno.find(params[:id])
  end

  def edit_password
    @aluno = Aluno.find(params[:aluno_id])
  end
  
  def update
    @aluno = Aluno.find(params[:id])
    if @aluno.update_attributes(aluno_params)
      flash[:success] = "Aluno atualizado"
      redirect_to @aluno    
    else
    render 'edit'
    end
  end

  def update_password
    @aluno = Aluno.find(params[:aluno_id])
    if @aluno.update_attributes(aluno_params)
      flash[:success] = "Senha atualizada"
      redirect_to @aluno    
    else
    render 'edit_password'
    end
  end

  def get_alterar_periodo
  end

  def alterar_periodo
    if params[:up]
      Aluno.all.each do |aluno|
        if aluno.periodo.to_i > 0
          aluno.update!(periodo: aluno.periodo.to_i + 1)
          flash[:success] = "Períodos aumentados em 1!"
        end
      end
    else
      Aluno.all.each do |aluno|
        if aluno.periodo.to_i > 0
          aluno.update!(periodo: aluno.periodo.to_i - 1)
          flash[:success] = "Períodos diminuidos em 1!"
        end
      end
    end
    redirect_to alterar_periodo_path
  end
  
  private
  
    def aluno_params
      params.require(:aluno).permit(:nome, :email, :matricula,
        :periodo, :password, :password_confirmation)
    end
  
end

app/helpers/alunos_helper.rb
module AlunosHelper
  
      # Returns the Gravatar for the given aluno.
  def gravatar_for_aluno(aluno, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(aluno.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: aluno.nome, class: "gravatar")
  end
  
end

app/views/alunos/_aluno.html.erb
<li>
  <%= gravatar_for_aluno aluno, size: 50 %>
  <%= link_to aluno.nome, aluno %>
  <% if current_user.admin? %>
    <%= link_to "excluir", aluno,
    method: :delete, data: { confirm: "You sure?" }, class: 'btn btn-danger', style:'margin-left:5px' %>
  <% end %>
</li>

app/views/alunos/_form_aluno.html.erb
<%= form_for(@aluno, url: yield(:path)) do |f| %> <!--#@aluno instance variable from controller-->

  <%= render 'shared/error_messages', object: f.object %>

  <%= f.label :nome %>
  <%= f.text_field :nome, value: nil, class: 'form-control' %>
  
  <%= f.label :email %>
  <%= f.text_field :email, value: nil, class: 'form-control' %>
  
  <%= f.label :matricula %>
  <%= f.text_field :matricula, value: nil, class: 'form-control' %>
  
  <%= f.label :periodo %>
  <%= f.text_field :periodo, value: nil, class: 'form-control' %>

  <%= f.label :senha %>
  <%= f.password_field :password, value: nil, class: 'form-control' %>

  <%= f.label :confirmação_de_senha %>
  <%= f.password_field :password_confirmation, value: nil, class: 'form-control' %>

  <%= f.submit yield(:button_text), class: "btn btn-primary" %>
<% end %>

app/views/alunos/_form_update_aluno.html.erb
<%= form_for(@aluno, url: yield(:path)) do |f| %> <!--#@aluno instance variable from controller-->

  <%= render 'shared/error_messages', object: f.object %>

  <%= f.label :nome %>
  <%= f.text_field :nome, class: 'form-control' %>
  
  <%= f.label :email %>
  <%= f.text_field :email, class: 'form-control' %>
  
  <%= f.label :matricula %>
  <%= f.text_field :matricula, class: 'form-control' %>

  <%= f.label :periodo %>
  <%= f.text_field :periodo, class: 'form-control' %>

  <%= f.submit yield(:button_text), class: "btn btn-primary" %>
<% end %>

app/views/alunos/_form_update_aluno_password.html.erb
<%= form_for(@aluno, url: yield(:path)) do |f| %> <!--#@aluno instance variable from controller-->

  <%= render 'shared/error_messages', object: f.object %>

  <%= f.label :nova_senha %>
  <%= f.password_field :password, class: 'form-control' %>

  <%= f.label :confirmação_de_senha %>
  <%= f.password_field :password_confirmation, class: 'form-control' %>

  <%= f.submit yield(:button_text), class: "btn btn-primary" %>
<% end %>

app/views/alunos/edit.html.erb
<% provide(:title, 'Editar Aluno') %>
<% provide(:button_text, 'Salvar Alterações') %>
<% provide(:path, aluno_path(@aluno)) %>

<h1>Editar Aluno</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form_update_aluno' %>
  </div>
</div>

app/views/alunos/edit_password.html.erb
<% provide(:title, 'Redefinir senha de Aluno') %>
<% provide(:button_text, 'Salvar Alterações') %>
<% provide(:path, aluno_update_password_path(@aluno)) %>

<h1>Redefinir senha de Aluno</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form_update_aluno_password' %>
  </div>
</div>

app/views/alunos/get_alterar_periodo.html.erb
<% provide(:title, 'Alterar Periodo') %>

<h1>Alterar Periodo</h1>

<div>
	<%= link_to "Aumentar Período em 1" , alterar_periodo_path(up: true), method: :post, class: "btn btn-lg btn-primary", style: "margin-left:30px; margin-bottom:30px" %>
	<%= link_to "Diminuir Período em 1" , alterar_periodo_path(up: nil), method: :post, class: "btn btn-lg btn-danger", style: "margin-left:30px; margin-bottom:30px" %>
</div>

app/views/alunos/index.html.erb
<% provide(:title, 'Alunos') %>
<h1>Alunos</h1>

<div>
  <%= link_to "Cadastrar Aluno", new_aluno_path, class: "btn btn-lg btn-primary", style: "margin-left:30px"%>

<%= search_form_for @q, :html => { style: 'display: flex; margin: 2em' } do |f| %>
	<%= f.search_field :nome_cont, class: 'form-control', style:'width:300px', placeholder: 'Pesquisar Aluno...' %>
	<%= f.submit 'Pesquisar', class: "btn btn-primary", style: 'width: 200px; margin-left:10px;
	margin-bottom:1em' %>
<% end %>
</div>


<ul class="users">
  <%= render @alunos %>
  <%= will_paginate %>
</ul>


<script>
  localStorage.clear(); // not really necessary, just clear the tabs that've been stored on the alunos show page
</script>

app/views/alunos/new.html.erb
<% provide(:title, 'Adicionar Aluno') %>
<% provide(:button_text, 'Adicionar Aluno') %>
<% provide(:path, alunos_path) %>

<h1>Adicionar Aluno</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form_aluno' %>
  </div>
</div>

app/views/alunos/show.html.erb
<% provide(:title, @aluno.nome) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= gravatar_for_aluno @aluno %>
        <%= @aluno.nome %>
      </h1>
      <h1>
        <%= @aluno.email %>
      </h1>     
      <h1>
        <%= @aluno.matricula %>
      </h1>
      <div style='margin-top:40px'>
        <% if current_user.admin? %>
           <%= link_to "Editar Informações de Aluno", edit_aluno_path(@aluno), class: 'btn btn-primary', style: 'float: left; margin-right:10px' %>
           <%= link_to "Excluir Aluno", @aluno, #analogous aluno_path(@aluno)
           method: :delete, data: { confirm: "Você tem certeza que deseja excluir o aluno #{@aluno.nome}?" }, class: 'btn btn-danger', style: 'float: left' %>
           <%= link_to "Redefinir Senha de Aluno", aluno_edit_password_path(@aluno), class: 'btn btn-info', style: 'margin-left:60px; margin-top:10px' %>
           <% if @aluno.kits.first %>
            <%= link_to "Gerar Etiquetas do Aluno", kit_download_path(@aluno.kits.first, all_kits: true, format: "pdf"), style: 'margin-left:60px; margin-top:10px', target: "_blank", class: "btn btn-warning" %>
           <% end %>
        <% end %>
      </div>
    </section>
  </aside>
  <div class="col-md-8">
  <!-- Nav tabs -->
  <ul class="nav nav-tabs" role="tablist">
    <li role="presentation" class="active"><a href="#kits" aria-controls="kits" role="tab" data-toggle="tab">Kits</a></li>
    <li role="presentation"><a href="#historico" aria-controls="historico" role="tab" data-toggle="tab">Histórico</a></li>
  </ul>

  <!-- Tab panes -->
  <div class="tab-content">
    <div role="tabpanel" class="tab-pane active" id="kits">
      <h3>Kits Cadastrados (<%= @aluno.kits.count %>)   <%= link_to "Cadastrar Kit", new_aluno_kit_path(@aluno), class: "btn btn-lg btn-primary" %> </h3>
        <ol class="feeds">
          <%= render @kits %>
        </ol>
        <%= will_paginate @kits %>
    </div>
    <div role="tabpanel" class="tab-pane" id="historico">          
        <h3>Histórico de Transações para <%= @aluno.nome %> (<%= @aluno.feeds.count %>)</h3>
        <ol class="feeds">
          <%= render @feeds %>
        </ol>
        <%= will_paginate @feeds %>
    </div>
  </div>
  
  <script> 
$(function() { 
  $('a[data-toggle="tab"]').on('shown.bs.tab', function (e) {
      // save the latest tab; use cookies if you like 'em better:
      localStorage.setItem('lastTab', $(this).attr('href'));
  });

  // go to the latest tab, if it exists:
  var lastTab = localStorage.getItem('lastTab');
  if (lastTab) {
      $('[href="' + lastTab + '"]').tab('show');
  }
  
 // $(document).on('turbolinks:load', function() {

  // for bootstrap 3 use 'shown.bs.tab', for bootstrap 2 use 'shown' in the next line
  
  // looks for tab and do something on shown event of the given tab - For information about tab events, check http://getbootstrap.com/javascript/#tabs-events
    $('a[data-toggle="tab"]').on('show.bs.tab', function (e) {
      //  before the new tab has been shown, the code below verifies that the tab has changed and if the pagination is greater than one
      //  if so, it redirects to first page (1) of the new tab

      var currentUrl = window.location.href;
      
      if (currentUrl.indexOf('?page=') > -1){
        
        var lastPage = currentUrl.split('?')[1].split('=');
        lastPage.shift();

        if(lastPage != 1 && lastTab && lastTab != $(this).attr('href')){ //lastPage here is equal to params[page]
          var newUrl = location.href.replace("?page="+lastPage, "");
          window.location.href = newUrl;
        }        
      }
      
    });
 // });
})
</script>

  </div>
</div>