config/routes.rb
Rails.application.routes.draw do
  
  get '/angular', to: 'static_pages#angular' # Hello World
  
  root 'static_pages#home'
  
  get  '/help',    to: 'static_pages#help', as: 'helf' #esse helf serve para usar no helf_path e helf_url
  
  get  '/about',   to: 'static_pages#about'
  
  get  '/contact', to: 'static_pages#contact'
  
  get '/signup', to: 'users#new'
  
  post '/signup', to: 'users#create'
  
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  
  post 'authenticate_user', to: 'authentication#authenticate_user'
  post 'authenticate_aluno', to: 'authentication#authenticate_aluno'

  get 'alterar_periodo', to: 'alunos#get_alterar_periodo'
  post 'alterar_periodo', to: 'alunos#alterar_periodo'

  resources :users
  resources :alunos do
    get 'edit_password', to: 'alunos#edit_password'
    patch 'update_password', to: 'alunos#update_password'
    resources :kits,              shallow: :true, except: [:index] do
      resource :download, only: [:show]
    end
  end
  resources :feeds, only: [:create, :index]
  resources :kit_types
  
  get '/kits', to: 'kits#index'

end

app/models/kit.rb
class Kit < ApplicationRecord
     belongs_to :aluno
     belongs_to :kit_type
     has_many :feeds, dependent: :destroy
     dragonfly_accessor :image
     validates :aluno_id, presence: true

     def tipo
          if kit_type
               kit_type.type_name
          else
               nome + " - (Cadastre um tipo de caixa para este Kit!)"
          end
     end
end

app/models/kit_type.rb
class KitType < ApplicationRecord
    has_many :kits
    validates :type_name, uniqueness: true, presence: true, length: { in: 1..40 }
end

app/controllers/kits_controller.rb
class KitsController < ApplicationController
  
  before_action :logged_in_user, if: -> { !json_request? }
 # before_action :authenticate_request, if: -> { json_request? }

    def index
      @kits = Kit.paginate(page: params[:page], :per_page => 25)
    end
    
    def show
      @kit = Kit.find(params[:id])
      @feeds = @kit.feeds.paginate(page: params[:page], :per_page => 5)
    end
    
    def new
      @kit = Kit.new
      @aluno = Aluno.find_by(id: params[:aluno_id])
    end
    
    def create
      @aluno = Aluno.find_by(id: params[:aluno_id])
      @kit = @aluno.kits.build(kit_params)

      content = @aluno.matricula + ";" + @kit.kit_type.id.to_s
      
      qr_code_img = RQRCode::QRCode.new(content, :size => 3, :level => :h).to_img.
      resize(150, 150)

      if @kit.save && (@kit.update_attribute :image, qr_code_img.to_string)
        # 2012939548;17
        flash[:success] = "Kit created!"
        redirect_to @aluno
      else
        render 'new'
      end
    end
    
    def destroy
      aluno = Kit.find(params[:id]).aluno
      Kit.find(params[:id]).destroy
      flash[:success] = "Kit excluído!"
      redirect_to aluno
    end
    
    def edit
    @kit = Kit.find(params[:id])
    @aluno = @kit.aluno
    end
    
    def update
      @kit = Kit.find(params[:id])
      @aluno = @kit.aluno
      content = @aluno.matricula + ";" + kit_params[:kit_type_id]
      qr_code_img = RQRCode::QRCode.new(content.to_s, :size => 3, :level => :h).to_img.resize(150, 150)

      if @kit.update_attributes(kit_params) && (@kit.update_attribute :image, qr_code_img.to_string)
        flash[:success] = "Kit atualizado"
        redirect_to @kit    
      else
      render 'edit'
      end
    end

    private
 
      def kit_params
        params.require(:kit).permit(:kit_type_id)
      end 
      
    def json_request?
      request.format.json?
    end
      
end

app/helpers/kits_helper.rb
module KitsHelper
end

app/views/kits/_form_kit.html.erb
<%= form_for(@kit, url: yield(:path)) do |f| %>

  <%= render 'shared/error_messages', object: f.object %>
  
  <%= f.label :tipo_de_caixa %>
  <%= f.collection_select(:kit_type_id, KitType.order(:type_name), :id, :type_name) %>

  <%= f.submit yield(:button_text), class: "btn btn-primary" %>
<% end %>

app/views/kits/_kit.html.erb
<li id="kit-<%= kit.id %>">
  <%= link_to image_tag("toolbox-icon.png", size:"50", alt: "Kit Image", class:"gravatar"), kit.aluno %>
  <span class="user"><%= link_to kit.tipo, kit_path(kit) %></span>
  <span class="content"><%= kit.tipo %></span>
  <span class="timestamp">
    <br>
  </span>
</li>

app/views/kits/edit.html.erb
<% provide(:title, 'Editar Kit') %>
<% provide(:button_text, 'Confirmar Alterações') %>
<% provide(:path, kit_path(@kit)) %>

<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= link_to (gravatar_for_aluno @aluno), @aluno %>
        <%= link_to @aluno.nome, @aluno %>
      </h1>
      <h1>
        <%= @aluno.email %>
      </h1>     
      <h1>
        <%= @aluno.matricula %>
      </h1>
    </section>
  </aside>
    <div class="col-md-6">
      <h1> Editar kit </h1>
      <h1>
        <%=  @kit.tipo %>
        <%= link_to image_tag(@kit.image.url, alt: "QRCODE"),
          @kit.image.url, target: '_blank' %>
      </h1>
      <div>
        <%= render 'form_kit' %>
      </div>
    </div>
</div>

app/views/kits/index.html.erb
<% provide(:title, 'All kits') %>
<h1>All kits</h1>

<%= will_paginate %>

<ul class="users">
    <%= render @kits %>
</ul>

<%= will_paginate %>

app/views/kits/new.html.erb
<% provide(:title, 'Cadastrar Kit') %>
<% provide(:button_text, 'Cadastrar Kit') %>
<% provide(:path, aluno_kits_path) %>


<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= link_to (gravatar_for_aluno @aluno), @aluno %>
        <%= link_to @aluno.nome, @aluno %>
      </h1>
      <h1>
        <%= @aluno.email %>
      </h1>     
      <h1>
        <%= @aluno.matricula %>
      </h1>
    </section>
  </aside>
    <div class="col-md-6">
      <h1> Cadastrar kit</h1>
      <%= render 'form_kit' %>
    </div>
</div>

app/views/kits/pdf.html.erb
<div id="label-font">
  <% if Rails.env.development? %>
      <%= image_tag(Rails.root.join('public', 'system', 'dragonfly', 'development', "#{kit.image_uid}"), size: "67x67", alt: "QRCODE", class: "gravatar") %>
  <% else %>
      <%= image_tag('https://s3-sa-east-1.amazonaws.com/odontokits/' + "#{kit.image_uid}", size: "67x67", alt: "QRCODE", class: "gravatar") %>
  <% end %>
    <b> NOME: <%= kit.aluno.nome %> </b>
    <b style="display: block"> PERÍODO: <%= kit.aluno.periodo %> </b>
    <b> KIT: <%= kit.tipo %> </b>
    <div>
      <b style="color:red;font-size: 85%"> VALIDADE: 15 DIAS </b>
    </div>
</div>

<% if all_kits == "true" %>
  <% kits.each do |kit| %>
    <div id="label-font" style="margin-top: 0px">
      <% if Rails.env.development? %>
          <%= image_tag(Rails.root.join('public', 'system', 'dragonfly', 'development', "#{kit.image_uid}"), size: "67x67", alt: "QRCODE", class: "gravatar") %>
      <% else %>
          <%= image_tag('https://s3-sa-east-1.amazonaws.com/odontokits/' + "#{kit.image_uid}", size: "67x67", alt: "QRCODE", class: "gravatar") %>
      <% end %>
        <b> NOME: <%= kit.aluno.nome %> </b>
        <b style="display: block"> PERÍODO: <%= kit.aluno.periodo %> </b>
        <b> KIT: <%= kit.tipo %> </b>
        <div>
          <b style="display:block;color:red;font-size: 85%"> VALIDADE: 15 DIAS </b>
        </div>
    </div>
  <% end %>
<% end %>

app/views/kits/show.html.erb
<% provide(:title, @kit.aluno.nome + "'s " + @kit.tipo) %>
<div class="row">
  <aside class="col-md-4">

    <section class="user_info">
      <h1>
          <%= link_to image_tag("toolbox-icon.png", size:"50", alt: "Kit Image"), '#' %>
          <%= @kit.tipo %>
          <% if current_user.admin? %>
             <%= link_to "Editar Kit", edit_kit_path(@kit), class: 'btn btn-primary', style: 'float: right'%>
             <br>
             <%= link_to "Excluir Kit", @kit, #analogous kit_path(@kit)
             method: :delete, data: { confirm: "Você tem certeza que deseja excluir #{@kit.tipo}?" }, class: 'btn btn-danger', style: 'float: right'%>
          <% end %>
      </h1>
      <div class="img-thumbnail", id="margem"> 
          <%= link_to image_tag(@kit.image.url, alt: "QRCODE", class: "gravatar"),
          @kit.image.url, target: '_blank' %>
              <b style="visibility:hidden">Nome: this is just to fill in</b>
              <br>
              <b>Nome: </b> <%= @kit.aluno.nome %>
              <br>
              <b>Período: </b> <%= @kit.aluno.periodo %>
              <br>
              <b>Kit: </b> <%= @kit.tipo %>
      </div>
    </section>
    <div style="margin-left: 80px">
      <%= link_to "Gerar Etiqueta", kit_download_path(@kit, all_kits: false, format: "pdf"), target: "_blank", class: "btn btn-lg btn-primary" %>
    </div>
  </aside>
    <div class="col-md-8">  
    <h3>Histórico de Transações para <%= @kit.tipo %> (<%= @kit.feeds.count %>)</h3>
    <% if @kit.feeds.any? %>
      <ol class="feeds">
        <%= render @feeds %>
      </ol>
      <%= will_paginate @feeds %>
    <% end %>
  </div>
</div>