config/routes.rb
Rails.application.routes.draw do
  
  get '/angular', to: 'static_pages#angular' # Hello World
  
  root 'static_pages#home'
  
  get  '/help',    to: 'static_pages#help', as: 'helf' #esse helf serve para usar no helf_path e helf_url
  
  get  '/about',   to: 'static_pages#about'
  
  get  '/contact', to: 'static_pages#contact'
  
  get '/signup', to: 'users#new'
  
  post '/signup', to: 'users#create'
  
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  
  post 'authenticate_user', to: 'authentication#authenticate_user'
  post 'authenticate_aluno', to: 'authentication#authenticate_aluno'

  get 'alterar_periodo', to: 'alunos#get_alterar_periodo'
  post 'alterar_periodo', to: 'alunos#alterar_periodo'

  resources :users
  resources :alunos do
    get 'edit_password', to: 'alunos#edit_password'
    patch 'update_password', to: 'alunos#update_password'
    resources :kits,              shallow: :true, except: [:index] do
      resource :download, only: [:show]
    end
  end
  resources :feeds, only: [:create, :index]
  resources :kit_types
  
  get '/kits', to: 'kits#index'

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    Developed by <a href="https://github.com/mccard"> Matheus C. Cardoso</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About", '#' %></li>
      <li><%= link_to "Contact", '#' %></li>
      <li><a href="http://www.ufrn.br/">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "odontokits", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Ajuda", '#' %></li>
        <% if logged_in? %>
          <li><%= link_to "Alunos", alunos_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Conta <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Meu perfil", current_user %></li>
              <li><%= link_to "Configurações", edit_user_path(current_user) %></li>
              <li><%= link_to "Tipos de Caixa", kit_types_path %></li>
              <li><%= link_to "Alterar periodo de alunos", alterar_periodo_path %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Sair", logout_path, method: "delete" %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_rails_default.html.erb
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                                              'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= render 'layouts/rails_default' %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>
      <%= yield %>
      <%= csrf_meta_tags %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/layouts/kit_pdf.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="pdfkit-margin_top" content="0in"/>
  <meta name="pdfkit-margin_bottom" content="0.0in"/>
  <meta name="pdfkit-margin_right" content="0.0in"/>
  <meta name="pdfkit-margin_left" content="0.0in"/>
  <title>Kit <%= "#{kit.id}" %> </title>
  <style>
    <%= CompassRails.sprockets.find_asset('application.scss').to_s %>
  </style>
</head>
<body>
  <%= yield %>
</body>
</html>